# Generated by Django 6.0.5 on 2026-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Winlight_app', '0003_recentwork_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Check to feature inside the homepage loop slider. Uncheck to move to the standalone roster page.'),
        ),
    ]
