# Generated by Django 6.0.5 on 2026-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Winlight_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Feature on Homepage'),
        ),
        migrations.AddField(
            model_name='upcomingproject',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Feature on Homepage'),
        ),
    ]
