# Generated by Django 6.0.5 on 2026-05-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Winlight_app', '0002_article_is_featured_upcomingproject_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Check to display in the homepage carousel slider. Uncheck to move to the dedicated portfolio grid page.'),
        ),
    ]
